name: Build & Publish

on:
  push:
    branches:
      - root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1

        with:
          java-version: 16

      - name: Gradle (Build)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload artifacts (Main JAR)
        uses: actions/upload-artifact@v2

        with:
          name: Main JAR
          path: build/libs/*-all.jar

      - name: Upload artifacts (JARs)
        uses: actions/upload-artifact@v2

        with:
          name: JARs
          path: build/libs/*.jar
      - name: Authenticate docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ghcr.io/quiltservertools/axolotl:latest -t ghcr.io/quiltservertools/axolotl:${GITHUB_SHA} .
      - name: Push docker image (latest)
        run: docker push ghcr.io/quiltservertools/axolotl:latest
      - name: Push docker image
        run: docker push ghcr.io/quiltservertools/axolotl:${GITHUB_SHA}
